# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
# https://github.com/bcoe/conventional-release-labels
# https://dev.to/github/how-to-automatically-generate-release-notes-for-your-project-2ng8
# https://www.conventionalcommits.org/en/v1.0.0/

# github release pre-defined template
changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: 🚀 Features
      labels:
        - feature
    - title: 🐛 Bug Fixes
      labels:
        - fix
        - bug
    - title: ♻️ Changes
      labels:
        - changed
        - enhancement
        - refactor
    - title: ⛔️ Deprecated
      labels:
        - deprecated
    - title: 🗑 Removed
      labels:
        - removed
    - title: 🔐 Security
      labels:
        - security
    - title: 📄 Documentation
      labels:
        - docs
        - documentation
    - title: 🧩 Dependency Updates
      labels:
        - deps
        - dependencies
    - title: 🧰 Maintenance
      label: 'chore'
    - title: 🧺 Miscellaneous #Everything except ABAP
      label: misc
    - title: Other Changes
      labels:
        - "*"
