name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  ## What Changed 👀
  $CHANGES
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
categories:
- title: 🚀 Features
  labels:
  - feature
  - feat
- title: ♻️ Enhancement
  labels:
  - enhancement
  - refactor
- title: 🐛 Bug Fixes
  labels:
  - fix
  - bug
- title: 👷 CI
  labels:
  - ci
  - ci-cd
  - devops
- title: ⚠️ Breaking Changes
  labels:
  - breaking-changes
  - major
- title: ⛔️ Deprecated
  labels:
  - deprecated
- title: 🗑 Removed
  labels:
  - removed
- title: 🔐 Security
  labels:
  - security
- title: 🎨 Style & Formatting
  labels:
  - style
- title: 🧪 Test
  labels:
  - test
- title: 📄 Documentation
  labels:
  - docs
  - documentation
- title: 🧩 Dependency Updates
  labels:
  - deps
  - build
  - dependencies
- title: 🧰 Maintenance
  label: 'chore'
- title: 🧺 Miscellaneous #Everything except ABAP
  label: misc
- title: 🚩 Other changes

autolabeler:
- label: 'chore'
  branch:
  - '/^(chore)(\([a-z ]+\))?\/.+/'
  title:
  - '/^(chore)(\([a-z ]+\))?: .+/'
- label: 'enhancement'
  branch:
  - '/^(refactor)(\([a-z ]+\))?\/.+/'
  title:
  - '/^(refactor)(\([a-z ]+\))?: .+/'
- label: 'documentation'
  branch:
  - '/^(docs)(\([a-z ]+\))?\/.+/'
  title:
  - '/^(docs)(\([a-z ]+\))?: .+/'
- label: 'ci-cd'
  branch:
  - '/^(ci)(\([a-z ]+\))?\/.+/'
  title:
  - '/^(ci)(\([a-z ]+\))?: .+/'
- label: 'test'
  branch:
  - '/^(test)(\([a-z ]+\))?\/.+/'
  title:
  - '/^(test)(\([a-z ]+\))?: .+/'
- label: 'bug'
  branch:
  - '/^(fix)(\([a-z ]+\))?\/.+/'
  title:
  - '/^(fix)(\([a-z ]+\))?: .+/'
- label: 'style'
  branch:
  - '/^(style)(\([a-z ]+\))?\/.+/'
  title:
  - '/^(style)(\([a-z ]+\))?: .+/'
- label: 'feature'
  branch:
  - '/^(feat)(\([a-z ]+\))?\/.+/'
  title:
  - '/^(feat)(\([a-z ]+\))?: .+/'
- label: 'minor'
  branch:
  - '/^(feat)(\([a-z ]+\))?\/.+/'
  title:
  - '/^(feat)(\([a-z ]+\))?: .+/'
- label: 'patch'
  branch:
  - '/^(fix)(\([a-z ]+\))?\/.+/'
  - '/^(ci)(\([a-z ]+\))?\/.+/'
  title:
  - '/^(fix)(\([a-z ]+\))?: .+/'
  - '/^(ci)(\([a-z ]+\))?: .+/'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
    - breaking-changes
  minor:
    labels:
    - minor
  patch:
    labels:
    - patch
  default: patch
exclude-labels:
- skip-changelog
