// Code generated by "stringer -type=Error -trimprefix=Error"; DO NOT EDIT.

package mediator

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorRequestHandlerAlreadyExists-1]
	_ = x[ErrorRequestPipelineBehaviorAlreadyExists-2]
	_ = x[ErrorRequestHandlerNotFound-3]
	_ = x[ErrorRequestHandlerNotValid-4]
	_ = x[ErrorNotificationHandlerNotValid-5]
}

const _Error_name = "RequestHandlerAlreadyExistsRequestPipelineBehaviorAlreadyExistsRequestHandlerNotFoundRequestHandlerNotValidNotificationHandlerNotValid"

var _Error_index = [...]uint8{0, 27, 63, 85, 107, 134}

func (i Error) String() string {
	i -= 1
	if i >= Error(len(_Error_index)-1) {
		return "Error(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Error_name[_Error_index[i]:_Error_index[i+1]]
}
