// Code generated by "stringer -type=tError -trimprefix=Error -output=error_string.go"; DO NOT EDIT.

package mediator

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorRequestHandlerAlreadyExists-1]
	_ = x[ErrorRequestPipelineBehaviorAlreadyExists-2]
	_ = x[ErrorRequestHandlerNotFound-3]
	_ = x[ErrorRequestHandlerNotValid-4]
	_ = x[ErrorNotificationHandlerNotValid-5]
}

const _tError_name = "RequestHandlerAlreadyExistsRequestPipelineBehaviorAlreadyExistsRequestHandlerNotFoundRequestHandlerNotValidNotificationHandlerNotValid"

var _tError_index = [...]uint8{0, 27, 63, 85, 107, 134}

func (i tError) String() string {
	i -= 1
	if i >= tError(len(_tError_index)-1) {
		return "tError(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _tError_name[_tError_index[i]:_tError_index[i+1]]
}
