name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  pre-checks:
    name: Pre-Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Conventional Commits Check
        uses: amannn/action-semantic-pull-request@v5
        # Only run on pull request events
        if: github.event_name == 'pull_request'
        id: check-pull-request-title-conventional-commits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest

  build-test:
    runs-on: ubuntu-latest
    needs: pre-checks
    steps:
      - uses: actions/checkout@v4

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: build
        run: go build -v ./...

      - name: test
        run: go test -v -coverprofile=profile.cov ./...

      - name: send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
