name: CI

on:
  push:
    branches: [ "main, dev" ]
  pull_request:
    branches: [ "main, dev" ]

jobs:

  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: setup go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: build
      run: go build -v ./...

    - name: test
      run: go test -v -coverprofile=profile.cov ./...

    - name: send coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: profile.cov

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
