name: First interaction
on:
  pull_request_target:
    types: 
      - opened
  issues:
    types:
      - opened

jobs:
  first-interaction:
    runs-on: ubuntu-latest
    name: First interaction
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome to ecommerece-microservice. Thank you ${{ github.event.pull_request.user.login }} for reporting your first issue. Please check out our [contributor guide](https://github.com/mehdihadeli/ecommerce-microservices/blob/develop/CONTRIBUTION.md).'          
        pr-message: 'Thank you ${{ github.event.pull_request.user.login }} for your first pull request to ecommerece-microservice repository. Please check out our [contributors guide](https://github.com/mehdihadeli/ecommerce-microservices/blob/develop/CONTRIBUTION.md).'
